#!/usr/bin/env bash

# exit script if any command fails
set -e
set -o pipefail

RDIR=$(git rev-parse --show-toplevel)

usage() {
    echo "Usage: ${0} [OPTIONS]"
    echo ""
    echo "Helper script to initialize repository that wraps other scripts."
    echo "Sets up conda environment, initializes submodules, and installs toolchain collateral."
    echo ""
    echo "Options"
    echo "  --help -h              : Display this message"
    echo "  --unpinned-deps -ud    : Use unpinned conda environment"
    echo "  --skip-conda           : Skip conda env creation"
    echo "  --skip-repositories    : Skip building extra RISC-V toolchain collateral (Spike, PK, tests, libgloos)"
    exit "$1"
}

USE_PINNED_DEPS=true
SKIP_CONDA=false
SKIP_REPOSITORIES=false

RISCV_TOOLS="$(dirname $(readlink -f $0))/../../.conda-env/riscv-tools"

if [ ! -e "${RISCV_TOOLS}" ]; then
    echo "Chipyard/FireSim must be fully setup before FireMarshal!" >&2
    exit 1
fi

RISCV_TOOLS=$(readlink -f "${RISCV_TOOLS}")

# getopts does not support long options, and is inflexible
while [ "$1" != "" ];
do
    case $1 in
        -h | --help )
            usage 3 ;;
        -ud | --unpinned-deps )
            USE_PINNED_DEPS=false ;;
        --skip-conda)
            SKIP_CONDA=true ;;
        --skip-repositories)
            SKIP_REPOSITORIES=true ;;
        * )
            error "invalid option $1"
            usage 1 ;;
    esac
    shift
done

if [ "$SKIP_CONDA" = false ]; then
    # note: lock file must end in .conda-lock.yml - see https://github.com/conda-incubator/conda-lock/issues/154
    CONDA_REQS=$RDIR/conda-reqs
    if [ "$USE_PINNED_DEPS" = false ]; then
        conda-lock -f $CONDA_REQS/firemarshal.yaml --lockfile $CONDA_REQS/firemarshal.conda-lock.yml
    fi
    conda-lock install -p $RDIR/.conda-env $CONDA_REQS/firemarshal.conda-lock.yml

    source $RDIR/.conda-env/etc/profile.d/conda.sh
    conda activate $RDIR/.conda-env
fi

if [ "$SKIP_REPOSITORIES" = false ]; then
	$RDIR/init-submodules.sh
fi

cat << EOT > env.sh
# line auto-generated by $0
conda activate $RDIR/.conda-env

export RISCV=${RISCV_TOOLS}
[[ ":\$PATH:" != *":\${RISCV}/bin:"* ]] && PATH="\${RISCV}/bin:\${PATH}"

echo "WARNING: Source the Chipyard/FireSim environment when done with FireMarhal!
EOT
