#!/bin/sh

SYSLOGD_ARGS=-n
KLOGD_ARGS=-n

start() {
    if [ -s "/autostart.sh" ]; then
        echo "Launch autostart script..."
        echo "/autostart.sh "
        /autostart.sh 
        ret=$?
        if [ $ret -eq 0 ]; then
            echo "Autostart script done!"
        else
            echo "Autostart script retured non-zero exit code ($ret)"
        fi
    fi
}

case "$1" in
  start)
  start
  ;;
  stop)
  #stop
  ;;
  restart|reload)
  start
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac

exit